name: Check with Lighthouse CI

on: [push]

env:
  BUILD_PATH: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dest
        id: cache-dest
        uses: actions/cache@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist
          key: ${{ runner.os }}-${{ github.run_number }}-dest

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: ${{ env.BUILD_PATH }}/yarn.lock

      - name: Install dependencies
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          yarn install
        
      - name: Build with Astro
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          yarn build
          yarn pagefind
          
  lighthouseci-mobile:
    name: Lighthouse CI Mobile
    needs: build
    runs-on: ubuntu-latest
    # Follow the environment name defined in repository settings
    environment: development 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cached dest
        id: cache-dest-restore
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist
          key: ${{ runner.os }}-${{ github.run_number }}-dest

      - name: Install LHCI
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          yarn global add @lhci/cli@0.12.x

      - name: Run Lighthouse CI
        run: |
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lighthouseci-report-mobile
          path: ${{ env.BUILD_PATH }}/.lighthouseci


  lighthouseci-desktop:
    name: Lighthouse CI Desktop
    needs: build
    runs-on: ubuntu-latest
    # Follow the environment name defined in repository settings
    environment: development 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cached dest
        id: cache-dest-restore
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist
          key: ${{ runner.os }}-${{ github.run_number }}-dest

      - name: Install LHCI
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          yarn global add @lhci/cli@0.12.x
          
      - name: Run Lighthouse CI
        run: |
          lhci autorun --config=lighthouserc-desktop.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lighthouseci-report-desktop
          path: ${{ env.BUILD_PATH }}/.lighthouseci