name: Check with Lighthouse CI

# This workflow is triggered manually
on:
  workflow_dispatch:   

env:
  BUILD_PATH: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dest
        id: cache-dest
        uses: actions/cache@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist
          key: ${{ runner.os }}-${{ github.run_number }}-dest

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          yarn config get enableImmutableInstalls
          yarn config set -H enableImmutableInstalls false
          yarn set version 4.3.0
          yarn install
        
      - name: Build with Astro
        working-directory: ${{ env.BUILD_PATH }}
        run: yarn build

      - name: Setup pagefind
        working-directory: ${{ env.BUILD_PATH }}
        run: yarn pagefind
          
  lighthouseci-mobile:
    name: Lighthouse CI Mobile
    needs: build
    runs-on: ubuntu-latest
    # Follow the environment name defined in repository settings
    environment: development 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cached dest
        id: cache-dest-restore
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist
          key: ${{ runner.os }}-${{ github.run_number }}-dest

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup yarn version
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          yarn config get enableImmutableInstalls
          yarn config set -H enableImmutableInstalls false
          yarn set version 4.3.0

      - name: Run Lighthouse CI
        run: |
          yarn dlx @lhci/cli@0.13.x autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lighthouseci-report-mobile
          path: ${{ env.BUILD_PATH }}/.lighthouseci


  lighthouseci-desktop:
    name: Lighthouse CI Desktop
    needs: build
    runs-on: ubuntu-latest
    # Follow the environment name defined in repository settings
    environment: development 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cached dest
        id: cache-dest-restore
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist
          key: ${{ runner.os }}-${{ github.run_number }}-dest
      
      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup yarn version
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          yarn config get enableImmutableInstalls
          yarn config set -H enableImmutableInstalls false
          yarn set version 4.3.0
          
      - name: Run Lighthouse CI
        run: |
          yarn dlx @lhci/cli@0.13.x autorun --config=lighthouserc-desktop.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lighthouseci-report-desktop
          path: ${{ env.BUILD_PATH }}/.lighthouseci